name: DungeonCore
version: 1.0. 0
main: com.multiverse.dungeon.DungeonCore
description: "완벽한 던전 시스템 플러그인"
author: junggyeol4444
website: "https://github.com/multiverse/dungeon"

# 커맨드
commands:
  dungeon:
    description: "던전 커맨드"
    usage: "§e/dungeon [list|info|enter|leave|stats|ranking|admin]"
    aliases: [dun, d]
    permission: dungeon.use

  party:
    description: "파티 커맨드"
    usage: "§e/party [create|invite|accept|reject|kick|leave|promote|disband|info|members]"
    aliases: [p]
    permission: party.use

# 권한
permissions:
  dungeon.use:
    description: "기본 던전 커맨드 사용"
    default: true
  
  dungeon.admin:
    description: "던전 관리 권한"
    default: op
  
  dungeon.admin.create:
    description: "던전 생성 권한"
    default: op
  
  dungeon.admin.delete:
    description: "던전 삭제 권한"
    default: op
  
  dungeon.admin.reload:
    description: "던전 재로드 권한"
    default: op
  
  party.use:
    description: "기본 파티 커맨드 사용"
    default: true
  
  party. admin:
    description: "파티 관리 권한"
    default: op

# 선택사항
depend: []
softdepend:
  - MythicMobs
  - EconomyCore
  - PlayerDataCore
  - CombatCore
  - QuestCore
  - MultiverseCore
  - WorldEdit
  - WorldGuard

# 로드 순서
load: POSTWORLD